# Generated by Django 2.2 on 2020-01-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comented', to='app.Message'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commented', to='app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messaged', to='app.User'),
        ),
    ]
